### ISSUE TITLE
能否启动桌面环境，现在只有webshell吧

### ISSUE THREAD

**Issue by jingle0927** [instantbox/instantbox#17]

**Comment by hileix** [comment]
不能，目前只支持 web 端
以后会考虑支持桌面端

**Comment by jingle0927** [comment]
@hileix  谢谢  期待

**Comment by wei** [comment]
@jingle0927 现在就可以安装桌面。造机器时开启5901端口，然后安装桌面和 vncserver。可以直接通过 vnc 连接桌面。已测试成功。

**Comment by import-yuefeng** [comment]
这倒是一个有趣的办法🤣

**Comment by import-yuefeng** [comment]
> @jingle0927 现在就可以安装桌面。造机器时开启5901端口，然后安装桌面和配套的vncserver。可以直接通过 vnc 连接桌面。已测试成功。

目前实现的VNC是shell的, 好像他好像是考虑想搞一个GUI那种吧🤣

**Comment by wei** [comment]
如果未来网页端有需要支持桌面的话，可以使用 WebShell + [noVNC](https://github.com/novnc/noVNC) 的解决方案。🍻

**Comment by import-yuefeng** [comment]
> 如果未来网页端有需要支持桌面的话，可以使用 WebShell + [noVNC](https://github.com/novnc/noVNC) 的解决方案。🍻

noVNC 真香, 之前还在考虑用户是否需要本地有VNC
