### ISSUE TITLE
本地部署创建容器后不能跳出web页面

### ISSUE THREAD

**Issue by d1107398473** [instantbox/instantbox#20]
本地部署成功后，新建容器点击打开web页面时跳转到101.67.162.14地址的随机端口，并不打开webshell，请大佬修复。（我是一只厚脸皮的伸手党。。）

**Comment by import-yuefeng** [comment]
请贴上具体的错误信息以及使用的系统等版本信息方便重现

**Comment by d1107398473** [comment]
![image](https://user-images.githubusercontent.com/28522923/51293167-97e75b00-1a48-11e9-8023-3e5e6cd64694.png)
![image](https://user-images.githubusercontent.com/28522923/51293176-a0d82c80-1a48-11e9-844f-564d50cee4c1.png)
容器创建成功后点击打开已创建的系统会跳转到101.67.162.14的随机端口。本地部署系统版本Ubuntu 16.04.5 LTS

**Comment by import-yuefeng** [comment]
请使用web 开发者工具对打开的页面进行网络分析, 并截图.

在一些极端情况下会出现建立web-shell失败的情况, 如果该问题持续出现, 目前推荐可以清理浏览器缓存, 并保持使用较新版本chrome/firefox浏览器再重试.

此外请使用docker logs inspire_nginx, docker logs inspire_flask, 贴上日志以便于进一步分析错误原因.

**Comment by LDJ4cob** [comment]
> 请使用web 开发者工具对打开的页面进行网络分析, 并截图.
> 
> 在一些极端情况下会出现建立web-shell失败的情况, 如果该问题持续出现, 目前推荐可以清理浏览器缓存, 并保持使用较新版本chrome/firefox浏览器再重试.
> 
> 此外请使用docker logs inspire_nginx, docker logs inspire_flask, 贴上日志以便于进一步分析错误原因.

同学，最后一行"祝你通过super-inspire更加方便的接触linux和开源, 这是我们最大的梦想."这个"祝"字似乎应该是"愿"字才对 : )。
很棒的项目！

**Comment by d1107398473** [comment]
[log.txt](https://github.com/super-inspire/super-inspire-end/files/2767780/log.txt)

**Comment by d1107398473** [comment]
> > 请使用web 开发者工具对打开的页面进行网络分析, 并截图.
> > 在一些极端情况下会出现建立web-shell失败的情况, 如果该问题持续出现, 目前推荐可以清理浏览器缓存, 并保持使用较新版本chrome/firefox浏览器再重试.
> > 此外请使用docker logs inspire_nginx, docker logs inspire_flask, 贴上日志以便于进一步分析错误原因.
> 
> 同学，最后一行"祝你通过super-inspire更加方便的接触linux和开源, 这是我们最大的梦想."这个"祝"字似乎应该是"愿"字才对 : )。
> 很棒的项目！

小牛牛还是牛小妹-.-!

**Comment by import-yuefeng** [comment]
> [log.txt](https://github.com/super-inspire/super-inspire-end/files/2767780/log.txt)

的确, 日志看起来很正常, 请再次简述一下您的部署过程和部署环境, 例如:

并且贴上chrome中对新开的web-shell页面的网络分析情况, 如果发现ERR_CONTENT_LENGTH_MISMATCH 错误, 则请注意, 该问题暂时无法查明具体原因, 但是可以解决, 清空浏览器缓存并保持较新版本的chrome会大大降低该问题再次出现的可能性.

**Comment by import-yuefeng** [comment]
> > 请使用web 开发者工具对打开的页面进行网络分析, 并截图.
> > 在一些极端情况下会出现建立web-shell失败的情况, 如果该问题持续出现, 目前推荐可以清理浏览器缓存, 并保持使用较新版本chrome/firefox浏览器再重试.
> > 此外请使用docker logs inspire_nginx, docker logs inspire_flask, 贴上日志以便于进一步分析错误原因.
> 
> 同学，最后一行"祝你通过super-inspire更加方便的接触linux和开源, 这是我们最大的梦想."这个"祝"字似乎应该是"愿"字才对 : )。
> 很棒的项目！

非常感谢鼓励: ) , 我们将会尽快解决这个语病问题, 如果您有兴趣, 欢迎提交pr

**Comment by d1107398473** [comment]
> > [log.txt](https://github.com/super-inspire/super-inspire-end/files/2767780/log.txt)
> 
> 的确, 日志看起来很正常, 请再次简述一下您的部署过程和部署环境
> 
> 并且贴上chrome中对新开的web-shell页面的网络分析情况, 如果发现ERR_CONTENT_LENGTH_MISMATCH 错误, 则请注意, 该问题暂时无法查明具体原因, 但是可以解决, 清空浏览器缓存并保持较新版本的chrome会大大降低该问题再次出现的可能性.

对于新开的webshell并没有网络分析，就是点击按钮打开新建标签页地址栏自动填入101.67.162.14该IP和新建容器的端口。该url肯定是不可达的，我的本地地址为192.168.10.138，部署过程与README一致，环境为Ubuntu 16.04.5 LTS+python3.5+docker18.06.1-ce

**Comment by d1107398473** [comment]
![image](https://user-images.githubusercontent.com/28522923/51309734-0b588f00-1a80-11e9-8448-18d5bfef8f5b.png)
![image](https://user-images.githubusercontent.com/28522923/51309769-1c090500-1a80-11e9-84b9-dec872f1b6d7.png)
我是在虚拟机上部署的，vmware使用的nat模式，webshell中应该绑定的地址应该是192.168.10.145+容器端口的，这里取成了我的外网出口IP地址。我的部署环境没有公网IP。

**Comment by import-yuefeng** [comment]
> ![image](https://user-images.githubusercontent.com/28522923/51309734-0b588f00-1a80-11e9-8448-18d5bfef8f5b.png)
> ![image](https://user-images.githubusercontent.com/28522923/51309769-1c090500-1a80-11e9-84b9-dec872f1b6d7.png)
> 我是在虚拟机上部署的，vmware使用的nat模式，webshell中应该绑定的地址应该是192.168.10.138+容器端口的，这里取成了我的外网出口IP地址。我的部署环境没有公网IP。我用我的vps试了下是可以成功部署的。我的需求是在局域网环境内使用--. (跪谢大佬积极跟进问题)

没关系~ 现在明确问题所在, 就是net模式引起的问题, 在我们还没更新新的版本之前, 最快的解决办法就是将SERVERURL改为常量, 例如你上面提到的192.168.10.138, 这个需求将在最近几天被完成.

**Comment by wei** [comment]
更新部署信息，现在 `init.sh` 会询问 IP 地址（选填）并自动设置环境变量 `SERVERURL`。
如果没填，那默认使用和网页相同的 IP / hostname。

https://github.com/instantbox/instantbox/blob/10b2b93b5d11cb13cbd61c03a4cd42be88847e95/init.sh#L31-L37
