### ISSUE TITLE
资源隔离无效

### ISSUE THREAD

**Issue by moguv587** [instantbox/instantbox#22]
限制使用1核心512M

![](https://i.loli.net/2019/01/18/5c40b97faaa2f.jpg)

**Comment by import-yuefeng** [comment]
并非资源隔离无效, 而是由于隔离性不足引起的, "Namespace的6项隔离看似完整，实际上依旧没有完全隔离Linux资源，比如/proc 、/sys 、/dev/sd*等目录未完全隔离，SELinux、time、syslog等所有现有Namespace之外的信息都未隔离。"
具体可以参考: http://dockone.io/article/8148
以我启动1vCPU, 10MB Mem为例, 如何真正查看该容器可以使用的内存和CPU呢?
可以通过因为docker的资源隔离是通过CGroups实现的, 所以我们也可以依靠它来检查资源是否被正确隔离.
在启动的web-shell中执行:
# cat  /sys/fs/cgroup/cpu/cpu.cfs_quota_us
![image](https://user-images.githubusercontent.com/36234175/51355301-bb1a1500-1af1-11e9-8a5e-ab6d63e9052a.png)

返回的该值除以100000就是当前能够使用的最大核心数.
对于mem而言, 是限制使用最大mem, 所以你可以查到:
![image](https://user-images.githubusercontent.com/36234175/51355380-f6b4df00-1af1-11e9-94fb-89d1c8fbf546.png)

在具体的使用上, 我如何判断真的有如上限制?
在我当前的机器上, 执行一些如:
apt update, apt install -y nginx, nginx 
你就能看到和高内存限制不一样的情况
![image](https://user-images.githubusercontent.com/36234175/51356002-e7369580-1af3-11e9-8104-e17198818321.png)
这里借用早期测试的一张图来展现效果(该配置下运行速度真的太慢了.....)

以上, 证明CGoups实现的资源隔离非常优秀而且高效, 供参考.

**Comment by moguv587** [comment]
对docker不是很了解，见谅，只是我自建了一个后，扔个fork炸弹连母鸡一起炸了所以提这个问题
ubuntu 18.04

**Comment by import-yuefeng** [comment]
> 对docker不是很了解，见谅，只是我自建了一个后，扔个fork炸弹连母鸡一起炸了所以提这个问题
> ubuntu 18.04

🤣, 没事~ 这个问题真的很多人都不太深究的话都没注意到~
此外, 对于资源管理, 我们也在进一步研究, 欢迎讨论!
