### ISSUE TITLE
运行出现‘IndexError: list index out of range’报错

### ISSUE THREAD

**Issue by zgjsntsm** [instantbox/instantbox#26]
```
inspire_flask | Traceback (most recent call last):
inspire_flask |   File "./inspire.py", line 27, in <module>
inspire_flask |     SERVERURL = os.popen('curl ip.sb').readlines()[0].split('\n')[0]
inspire_flask | IndexError: list index out of range
```

好像是执行`curl ip.sb`获取ip地址出错了，但是我直接执行curl时是正常的，能正常获取ip

**Comment by import-yuefeng** [comment]
目前这个办法的确不是非常的优雅, 不过似乎我刚刚试了试没问题, 暂时解决办法是通过手动设置SERVERURL为所需常量.

![image](https://user-images.githubusercontent.com/36234175/51428416-5e784080-1c3e-11e9-95cf-c7a180a28e90.png)

这个问题将在下一个版本中和内网使用需求共同解决.
供参考

**Comment by zgjsntsm** [comment]
好的，目前就是手动设置的该常量解决的这个问题。

**Comment by wei** [comment]
更新了 `init.sh` 来询问 ip 地址并自动设置环境变量 `SERVERURL`。

https://github.com/instantbox/instantbox/blob/10b2b93b5d11cb13cbd61c03a4cd42be88847e95/init.sh#L31-L32
