### ISSUE TITLE
随机端口让 docker 自动分配

### ISSUE THREAD

**Issue by wei** [instantbox/instantbox#42]
```
--expose             |   Expose a port or a range of ports
--publish-all , -P   |   Publish all exposed ports to random ports
```

可以直接让 docker 分配端口

```
docker run -d --name container --expose 1588 --publish-all
```

p.s. 话说现在这个 randport 能从容器内查服务器外部端口打开情况吗？
https://github.com/instantbox/instantbox/blob/92fd313f06e693ee14ce904441c8b7f1c72f2d31/inspire.py#L158-L168

**Comment by import-yuefeng** [comment]
似乎是一个设计失误, 在封装好的docker 版本的inspire无法判断宿主机的端口是否被使用.
我建议存redis吧? 根据每次的create/rm API来维护host的端口占用情况.
(不过之前似乎很少出现这个问题, 没人提issue🤔

**Comment by wei** [comment]
嗯嗯 还是 2 比较优美 本来就是 docker 专门为这种 use case 设计的。
1 的话宿主机上运行别的东西就有冲突了 😄
