### ISSUE TITLE
关于image创建的问题

### ISSUE THREAD

**Issue by chinazhenzhen** [instantbox/instantbox#45]
我在WEB中申请一个Debian/jessie的系统，然后立即去服务器检查docker image的情况，发现新增了image。但是image却是7 hours之前新建的。为什么不是几分钟之前新建的image
![image](https://user-images.githubusercontent.com/30887156/53801936-7f40ef00-3f7b-11e9-8c7c-ee952342e811.png)

**Comment by import-yuefeng** [comment]
> 我在WEB中申请一个Debian/jessie的系统，然后立即去服务器检查docker image的情况，发现新增了image。但是image却是7 hours之前新建的。为什么不是几分钟之前新建的image
> ![image](https://user-images.githubusercontent.com/30887156/53801936-7f40ef00-3f7b-11e9-8c7c-ee952342e811.png)

那个是镜像最近的更新(build&&push)时间吧? 并不是你pull下来的时间~

**Comment by wei** [comment]
Image显示是上一次我们构建并发布的时间。

你新建的容器叫 container，不是 image。请使用 docker ps 查看。
