### ISSUE TITLE
Centos下使用systemctl报错

### ISSUE THREAD

**Issue by kafuuchino-desu** [instantbox/instantbox#46]
centos7的下使用systemctl会报错Failed to get D-Bus connection: Operation not permitted

**Comment by import-yuefeng** [comment]
docker官方推荐 **在一个容器内只运行一个进程**, 而systemctl服务管理是可以用于管理一系列'daemon service'的服务程序, 所以并不合适与推荐在容器内使用.

> systemd维护系统服务程序，它需要特权去会访问Linux内核。而容器并不是一个完整的操作系统，只有一个文件系统。

不过目前已经有办法在容器内使用systemctl, 请参考 https://hub.docker.com/r/centos/systemd 需要以特权模式下运行容器即可.

而该模式对于instantbox的无状态服务而言可能具有潜在性危险, 所以我们没有提供, 但是仍然可以通过修改API中的代码实现使用privileged模式运行docker容器, 继而可在容器内使用systemctl.


更多请参考:

- https://forum.huawei.com/enterprise/zh/thread-427747-1-1.html  (中文)
- https://linuxacademy.com/community/posts/show/topic/21629-docker-failed-to-get-dbus-connection-operation-not-permitted  (英文)
- https://hub.docker.com/r/centos/systemd  (CentOS官方支持systemctl的docker image)
