### ISSUE TITLE
无法创建linux镜像

### ISSUE THREAD

**Issue by SongJiaqiang** [instantbox/instantbox#48]
在http://35.220.214.188:8888 页面无法创建镜像，一直转菊花。
![image](https://user-images.githubusercontent.com/5006599/54655280-56ccff00-4afc-11e9-9c01-3723b314d67c.png)

**Comment by import-yuefeng** [comment]
应该是突然增加的访问压力超过了小鸡的承受能力🌚，我回去检查一下，需要赞助🌚🌚🌚

**Comment by wlmnzf** [comment]
emmm，在本地创建也比较慢呢

**Comment by import-yuefeng** [comment]
请注意，第一次创建要pull image

**Comment by wlmnzf** [comment]
> 请注意，第一次创建要pull image

原来如此，谢谢，很有意思的项目

**Comment by LittleFee** [comment]
要是开放资金赞助就好了，或者支付宝领红包也OK 啊

**Comment by import-yuefeng** [comment]
> 要是开放资金赞助就好了，或者支付宝领红包也OK 啊

如果您有意的话, 也可以发信到team@instantbox.org 🤣, 感觉支付宝领红包有点污染GitHub环境所以都没用. 资金是因为害怕没能将钱用好, 愧对赞助者

**Comment by import-yuefeng** [comment]
> 在http://35.220.214.188:8888 页面无法创建镜像，一直转菊花。
> ![image](https://user-images.githubusercontent.com/5006599/54655280-56ccff00-4afc-11e9-9c01-3723b314d67c.png)

问题应该修好了. 初步估计是因为CPU负载过大, 单核小鸡跑不动了233

**Comment by SongJiaqiang** [comment]
> > 要是开放资金赞助就好了，或者支付宝领红包也OK 啊
> 
> 如果您有意的话, 也可以发信到[team@instantbox.org](mailto:team@instantbox.org) 🤣, 感觉支付宝领红包有点污染GitHub环境所以都没用. 资金是因为害怕没能将钱用好, 愧对赞助者

好东西藏不住，可以把捐款用于购买服务器资源，访问量涨起来还是很恐怖的，不能让作者自己一个人承担。

**Comment by import-yuefeng** [comment]
> > > 要是开放资金赞助就好了，或者支付宝领红包也OK 啊
> > 
> > 
> > 如果您有意的话, 也可以发信到[team@instantbox.org](mailto:team@instantbox.org) 🤣, 感觉支付宝领红包有点污染GitHub环境所以都没用. 资金是因为害怕没能将钱用好, 愧对赞助者
> 
> 好东西藏不住，可以把捐款用于购买服务器资源，访问量涨起来还是很恐怖的，不能让作者自己承担。

昨晚GCP服务器超额, 挂了2333, 我最近去换一台.
