### ISSUE TITLE
怎么修改时间限制24小时？网页输入不能输入字母 只能数字

### ISSUE THREAD

**Issue by josercc** [instantbox/instantbox#49]
我部署在本地 但是无法创建超过24小时 我想让本地的存货时间长一些 怎么修改？
刚才新建看了一个服务 发现如法在网页输入字母命令

**Comment by import-yuefeng** [comment]
你好, 目前无法超过24小时是被写到了代码里的, 如果有兴趣增加更多时间上的问题, 可以简单修改代码即可.

[附上相关代码](https://github.com/instantbox/instantbox/blob/master/inspire.py#L102-L112)

此外, "刚才新建看了一个服务 发现如法在网页输入字母命令" 我没有理解您这段话的意思.

**Comment by josercc** [comment]
@import-yuefeng 对于修改24不对的 你还有静态网页也显示24了 你打包成了 image 改不了
对于网页是新增一个容器页面打开了终端 在里面我无法输入字母 只能输入数字

**Comment by import-yuefeng** [comment]
> @import-yuefeng 对于修改24不对的 你还有静态网页也显示24了 你打包成了 image 改不了
> 对于网页是新增一个容器页面打开了终端 在里面我无法输入字母 只能输入数字

无法输入字母问题没有重现, 抱歉无法告知具体原因和确定是否为bug.
打包成image, 但是我们提供了Dockerfile, 请自行修改code后重新build.

**Comment by ciphermagic** [comment]
你好，是不是把 `docker-compose.yml` 里的 `cron` 模块去掉再启动，就不会定时清理容器啦？

**Comment by wei** [comment]
是
