### ISSUE TITLE
友情提示不要公开提供服务，很容易被当肉鸡跟跳板的

### ISSUE THREAD

**Issue by jonwinters** [instantbox/instantbox#51]
友情提示不要公开提供服务，很容易被当肉鸡跟跳板的

**Comment by import-yuefeng** [comment]
> 友情提示不要公开提供服务，很容易被当肉鸡跟跳板的

决定提供非常受限的公开服务, 例如非登录状态打开的容器只有5分钟时效.
对注册进行限制. 大家也可以自己去部署一个更方便使用.
