### ISSUE TITLE
如果前端用nginx或负载均衡对外提供服务，怎么解决创建虚拟机的问题

### ISSUE THREAD

**Issue by fjnphsq** [instantbox/instantbox#54]
我今天尝试了下在内网部署了一个，确实很方便很好用，但是当我用nginx使用进行反向代理，同时用域名进行访问的时候，创建的虚拟机依旧返回的是内网ip和一个端口，这个未来是不是有什么解决方案？

**Comment by wei** [comment]
是的 之后会进行全程反代 不再需要访问端口
