### ISSUE TITLE
Add support for arbitrary Docker images

### ISSUE THREAD

**Issue by ndusart** [instantbox/instantbox#56]
It would be great to be able to start a container for any image on an accessible registry or at least for the hoster to be able to easily add an arbitrary image in the list.

For example, there could be a script that detects on which distribution it is based, install ttyd on it and then starts ttyd. This script would be launched by replacing the CMD of the image to run.

**Comment by wei** [comment]
Please follow examples in [instantbox/instantbox-images](https://github.com/instantbox/instantbox-images) to prepare a custom image, then modify `manifest.json` to expose it as an option.
