### ISSUE TITLE
add support to commit docker images

### ISSUE THREAD

**Issue by rifkytech** [instantbox/instantbox#57]
I hope this can commit to the image before it is deleted

**Comment by wei** [comment]
What is the use case? What would you like to do with the commited image?

**Comment by rifkytech** [comment]
when I run a container to do an experiment, I have a problem when creating a new image so that my configuration is not lost, because instantbox does have a period of 24 hours to be active

**Comment by wei** [comment]
So you want the ability to both commit and a way to get back to launch the committed image again correct?

**Comment by rifkytech** [comment]
Good, thank you for responding & providing other solutions to this
