### ISSUE TITLE
反馈一个问题，请教一个问题

### ISSUE THREAD

**Issue by langtuteng17** [instantbox/instantbox#58]
1、反馈：首页面选择不是很友好，因为一般的用户打开首页之后，首先看到的是各个 Linux 系统的LOGO，往往第一反应就是点击图片试试，发现点击图片毫无反应，然后才能看到下面的灰色字体：选择系统版本。选择完毕之后图片变亮，我建议是鼠标放在图片上点击之后默认是选择此操作系统，然后进行提示选择系统版本。
2、请教：新建的系统每次端口都不一样，请问服务器需要开哪个范围的端口呢？

**Comment by wei** [comment]
1. 谢谢反馈 目前也在考虑更新一下设计实现 response design
2. 目前由 docker 自动选择端口是 30000-32767 一般docker会自动管理并开放端口 如果你的主机商有额外的防火墙那就得手动开一下端口
https://github.com/docker/swarmkit/blob/486ad69951868792367a503042ef3f55b399cc40/manager/allocator/cnmallocator/portallocator.go#L11-L17
