### ISSUE TITLE
选择系统无法创建

### ISSUE THREAD

**Issue by buyucoder** [instantbox/instantbox#59]
选择 Alpine 可以创建,选择其他的都一直在转,他是在docker上面拉取镜像吗?现在的进度也看不到,不知道要等到什么时候?

这个过程有没有什么解决方法?自己手动拉取?

![image](https://user-images.githubusercontent.com/11970360/55379060-2058a080-554e-11e9-859c-ca6c37fb5893.png)

**Comment by wei** [comment]
国内使用请配置国内镜像。可以手动拉取 instantbox/ubuntu

**Comment by buyucoder** [comment]
恩,刚刚拉取成功了,这几个比较大要等一会,谢谢
