### ISSUE TITLE
执行docker-compose up -d命令报错

### ISSUE THREAD

**Issue by linuxluyi** [instantbox/instantbox#60]
1。前几步命令都是成功执行了的，输入了 IP 和端口号，该执行系统提示的：docker-compose up -d 命令了，但是执行完之后就报错。
2。报错内容
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
检查，根目录下是有docker-compose.yml这个文件的
3.。系统版本 Centos 7.6.180,Docker 也是最新安装的，并且服务在启动状态

**Comment by wei** [comment]
请截图 ls -alt 再 docker-compose -v 再 docker-compose up -d

**Comment by langtuteng17** [comment]
1。第一张是又重新操作

![完全重新操作](https://raw.githubusercontent.com/langtuteng17/images/master/1.png)
2。执行你的回复，执行的命令分别是：ls -alt 再 cat docker-compose.yml 

![ls -alt cat docker-compose.yml ](https://raw.githubusercontent.com/langtuteng17/images/master/2.png)
3。继续执行你的回复命令 docker-compose -v 再 docker-compose up -d

![docker-compose -v 再 docker-compose up -d](https://raw.githubusercontent.com/langtuteng17/images/master/3.png)

**Comment by langtuteng17** [comment]
> 请截图以下: ls -alt 再 cat docker-compose.yml 再 docker-compose -v 再 docker-compose up -d

PS ：用的是 CentOS 物理机，不是云服务器

**Comment by wei** [comment]
麻烦手动重新安装一下 docker-compose
sudo rm $(which docker-compose)
sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

**Comment by import-yuefeng** [comment]
> 麻烦手动重新安装一下 docker-compose
> 
> ```
> sudo rm $(which docker-compose)
> sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
> sudo chmod +x /usr/local/bin/docker-compose
> ```
> 还不行的话试一下 docker-compose up -d -f ./docker-compose.yml

我看了半天, 也没瞅出这个奇怪的问题🤣

**Comment by wei** [comment]
Closed due to inactivity.
