### ISSUE TITLE
Add support for open port option while hitting /getOS api

### ISSUE THREAD

**Issue by anuragsarkar97** [instantbox/instantbox#66]
/getOS API should also take ideally a list of open ports to bind for use cases such as :

1. if someone wants to test some code which requires a server? a flask app maybe 
2. use it as an FTP server?

**Comment by wei** [comment]
getOS does take a port parameter. At this time we only support a single port to be exposed.

**Comment by anuragsarkar97** [comment]
can we add support for it? to build and test maybe backend applications?

**Comment by wei** [comment]
We already have support to expose one port. This one port can be used to test your backend application. Does that address your use-case? If not, What is your use-case?

**Comment by anuragsarkar97** [comment]
yes i got it. Thanks

**Comment by anuragsarkar97** [comment]
tho it seems that open port is binding to none.

**Comment by wei** [comment]
@anuragsarkar97 good eye. None simply means the docker engine will select a random host port for binding. please refer to docket python library for more information.
