### ISSUE TITLE
添加对SSL证书的支持等功能请求

### ISSUE THREAD

**Issue by hiouttime** [instantbox/instantbox#67]
因为公网环境需要域名访问,且开启HSTS,故望能支持指定SSL证书..
能够对已销毁的容器的端口重新利用,不然会一直叠加..
另外能否将tty端口复用?不太清楚具体的实现难度..

**Comment by wei** [comment]
RE: SSL 请添加一个 nginx 或者 caddy 反代并在上面配置 SSL

RE: 目前使用 docker 自带随机分配端口 默认自动叠加 应该是足够使用的 如果有用完无法分配端口的情况请报告

RE: ttyd 目前最新版已通过反代实现 不再是通过端口方式进行访问

**Comment by hiouttime** [comment]
https://github.com/instantbox/instantbox/commit/07371fda56b45a399e562ff421461344fff77e2e
已经支持?

**Comment by wei** [comment]
支持什么？麻烦具体一点。这个 commit 和上面三个问题及回复都没有关系

**Comment by hiouttime** [comment]
"ttyd 目前最新版已通过反代实现 不再是通过端口方式进行访问"

**Comment by hiouttime** [comment]
该新版ttyd是否已经集成到https://github.com/instantbox/instantbox/commit/07371fda56b45a399e562ff421461344fff77e2e内了?

**Comment by wei** [comment]
这个反代是 #63 https://github.com/instantbox/instantbox/commit/b6c7ccc965becf519a37828dc37313a3865285f4 并不加入 https 你需要再反代一层。
