### ISSUE TITLE
instantboxManager.py hint error

### ISSUE THREAD

**Issue by tufeiping** [instantbox/instantbox#70]
in file instantboxManager.py

```
raise Exception(
                'Could not load manifest.json. ' +
                'Download it from https://get.instantbox.org/manifest.json'
            )
```
but https://get.instantbox.org/manifest.json is not found

in Dockerfile .

`ADD https://raw.githubusercontent.com/instantbox/instantbox-images/master/manifest.json .
`
https://raw.githubusercontent.com/instantbox/instantbox-images/master/manifest.json is valid!

**Comment by wei** [comment]
Thanks! Fixed the https://get.instantbox.org/manifest.json link. 

https://raw.githubusercontent.com/instantbox/instantbox-images/master/manifest.json is valid.
