### ISSUE TITLE
why the kernel version still 3.10?

### ISSUE THREAD

**Issue by ZuoGuocai** [instantbox/instantbox#71]
I install  instantbox  in CentOS7 and launch a CentOS8  instance  in  isntantbox environment. But I find the kernel version was still
3.10  when I connect the  CentOS8 instance via webshell. I remember  the kernel version is 4.x in CentOS8. Is is a bug?

```
[root@instantbox_managed_omidwjl1xz9qg2v4 home]# cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)

[root@instantbox_managed_omidwjl1xz9qg2v4 home]#
[root@instantbox_managed_omidwjl1xz9qg2v4 home]# uname  -r
3.10.0-957.27.2.el7.x86_64
```

**Comment by wei** [comment]
docker uses host kernel. please try updating your host kernel and reboot.
