### ISSUE TITLE
允许超过24小时的宽限期。

### ISSUE THREAD

**Issue by Jobpick** [instantbox/instantbox#80]
你好，开发者，对比qemu，instantbox比较轻量化。但能否允许新建虚拟机超过24小时的宽限期？

**Comment by wei** [comment]
Hello, 只要移除 `docker-compose.yml` 内的 `cron` 服务即可以让服务器暂停自动删除任务。

https://github.com/instantbox/instantbox/blob/07371fda56b45a399e562ff421461344fff77e2e/docker-compose.yml#L24-L32

**Comment by Jobpick** [comment]
哦，非常感谢



---- 回复的原邮件 ----
| 发件人 | Wei ***@***.***> |
| 日期 | 2024年04月16日 10:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [instantbox/instantbox] 允许超过24小时的宽限期。 (Issue #80) |

Hello, 只要移除 docker-compose.yml 内的 cron 服务即可以让服务器暂停自动删除任务。

https://github.com/instantbox/instantbox/blob/07371fda56b45a399e562ff421461344fff77e2e/docker-compose.yml#L24-L32
